### ISSUE TITLE
Doc Layout Looks Weird

### ISSUE THREAD

**Issue by Nauxscript** [TinsFox/shadcnui-boilerplate#5]
As shown in the figure:
![image](https://github.com/user-attachments/assets/c79ef9ba-4e93-4358-a34d-b6a16857b758)

**Comment by TinsFox** [comment]
This seems to be a vitepress bug, I'll check it again

**Comment by TinsFox** [comment]
After a review of the tests, I found that this is a Vercel issue, I used GitHub Page and Cloudflare Page deployment is normal, only Vercel has layout issues.

Let’s temporarily migrate to Cloudflare Page to solve this problem. 

The new document domain name is https://shadcnui-boilerplate.pages.dev
