### ISSUE TITLE
getting-started link in the index.tsx seems point to a wrong place

### ISSUE THREAD

**Issue by einverne** [TinsFox/shadcnui-boilerplate#6]
After I run `yarn start` the index page shows a link point to 

```
https://github.com/TinsFox/vite-boilerplate/blob/main/docs/getting-started.md
```

but the link is actually 

```
https://github.com/TinsFox/shadcnui-boilerplate/blob/main/docs/zh/guide/getting-started.md
```

Should I create a PR to fix?

**Comment by TinsFox** [comment]
Thank you, I think to jump to `https://shadcnui-boilerplate-docs.vercel.app/guide/getting-started` will be more appropriate, if you are willing to create a PR

**Comment by einverne** [comment]
It looks like you already fix the wrong link, so I will close the issue.

by the way, the https://shadcnui-boilerplate-docs.vercel.app/guide/getting-started sidebar looks strange in Chrome.
<img width="821" alt="image" src="https://github.com/user-attachments/assets/05b58da0-868b-4857-b4e8-d7bd7d505201">

**Comment by TinsFox** [comment]
I'm troubleshooting this issue #5
